# ============================== Filebeat inputs ===============================

filebeat.inputs:
  - type: filestream
    id: request
    enabled: true
    paths:
      - 'C:\projects\Privat\R2Northstar-MapSystem\log\application.log'

# ============================== Filebeat modules ==============================

# ======================= Elasticsearch template setting =======================
setup.template.enabled: false

# ================================== General ===================================
setup.ilm.enabled: false

# ================================= Dashboards =================================
setup.dashboards.enabled: false

# ================================== Outputs ===================================

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
  allow_older_versions: true
  index: "r2ts-application-log-%{+yyyy.MM.dd}"

# ------------------------------ Logstash Output -------------------------------

# ================================= Processors =================================
#2022-05-29 22:17:29|INFO |ApplicationStartUp:79|-|Application ready post event took: 0 ms
processors:
  - dissect:
      tokenizer: "%{timestamp|string}|%{level|string}|%{class|string}|%{requestId|string}|%{message|string}"
      target_prefix: "segment"
  - drop_fields:
      fields: ["agent", "log", "input", "host", "ecs", "message" ]


