# ============================== Filebeat inputs ===============================

filebeat.inputs:
  - type: filestream
    id: request
    enabled: true
    paths:
      - 'C:\projects\Privat\R2Northstar-MapSystem\log\application.log'

# ============================== Filebeat modules ==============================

# ======================= Elasticsearch template setting =======================
setup.template.enabled: false

# ================================== General ===================================
setup.ilm.enabled: false

# ================================= Dashboards =================================
setup.dashboards.enabled: false

# ================================== Outputs ===================================

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
  allow_older_versions: true
  index: "log-application-r2tss-%{+yyyy.MM.ww.DDD}-v1"

# ------------------------------ Logstash Output -------------------------------

# ================================= Processors =================================
#2023-07-29 17:33:21|DEBUG|JobRunnerSchedulerService:64|abbb9c0a-0cb4-4ae8-a9d2-5fdb30aa49be|Startup|3|fc31aa73-2258-44f9-add6-62b45212c9c8|ApplicationPostReadyEvent processed
processors:
  - dissect:
      tokenizer: "%{timestamp|string}|%{level|string}|%{class|string}|%{instance|string}|%{contextType|string}|%{requestId|string}|%{traceId|string}|%{message|string}"
      target_prefix: "segment"
  - drop_fields:
      fields: ["agent", "log", "input", "host", "ecs", "message" ]


