version: '3.9'

services:
  t2-ts-dataendpoint-base-db:
    build:
      context: ../../..
      dockerfile: install/docker/Dockerfile
    ports:
    - 8090:8090
    - 5432:5432
    env_file:
    - container.env
    depends_on:
    - "database"
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: DBACC # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: DBACC # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: R2-TS # The PostgreSQL default database (automatically created at first launch)
