version: '3.9'

services:
  r2-gs-frontend:
    build:
      context: ../../..
      dockerfile: install/docker/Dockerfile
    ports:
    - "3000:3000"
    networks:
      - r2-ts
networks:
  r2-ts:
    external: true
