elastic:
    nodes:
        - ${org.elastic.node.0}
    prefix: tfms
server:
    port: 8090
javax:
    sql:
        DataSource:
            MainDataSource:
                dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
                dataSource:
                    url: ${javax.persistence.jdbc.url}
                    user: ${javax.persistence.jdbc.user}
                    password: ${javax.persistence.jdbc.password}
