r2ts:
  shouldSaveNpcPosition: false
  heatmap.pixelDensity: 4
  match:
    event:
      NpcPosition:
        modulo: 1000


elastic:
    nodes:
        - ${org.elastic.node.0}
    enabled: ${org.elastic.enabled}
    postfix: r2ts
    embedded:
      autostart: ${org.elastic.enabled}
server:
    port: 8090
javax:
    sql:
        DataSource:
            MainDataSource:
                dataSourceClassName: ${javax.persistence.jdbc.dataSourceClassName}
                dataSource:
                    url: ${javax.persistence.jdbc.url}
                    user: ${javax.persistence.jdbc.user}
                    password: ${javax.persistence.jdbc.password}
request.recorder:
  HttpRequestDetails.enabled: true
  QueueRequestDetails.enabled: true
  SchedulerRequestDetails.enabled: true
  StartupRequestDetails.enabled: true
  WebsocketRequestDetails.enabled: false
caffeine:
  default:
    expireAfterSeconds: 86400 # 1 day
  instances:
    playerLookUp:
      expireAfterSeconds: 43200 # 6 hours
    matchStatsCache:
      expireAfterSeconds: 120 # 2 min
#mp:
#  messaging:
#    connector.helidon-jms:
#      jndi:
#        jms-factory: ConnectionFactory
#        env-properties:
#          java.naming:
#            factory.initial: org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory
#            provider.url: ${org.apache.activemq.url}
#    incoming:
#      from-indexingQueue:
#        connector: helidon-jms
#        destination: indexingQueue
#        type: queue
#      from-heatmapGeneration:
#        connector: helidon-jms
#        destination: heatmapGeneration
#        type: queue
#    outgoing:
#      to-indexingQueue:
#        connector: helidon-jms
#        destination: indexingQueue
#        type: queue
#      to-heatmapGeneration:
#        connector: helidon-jms
#        destination: heatmapGeneration
#        type: queue