elastic:
    nodes:
        - ${org.elastic.node.0}
    prefix: r2ts
    enabled: ${org.elastic.enabled}
server:
    port: 8090
javax:
    sql:
        DataSource:
            MainDataSource:
                dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
                dataSource:
                    url: ${javax.persistence.jdbc.url}
                    user: ${javax.persistence.jdbc.user}
                    password: ${javax.persistence.jdbc.password}
mp:
  messaging:
    connector.helidon-jms:
      jndi:
        jms-factory: ConnectionFactory
        env-properties:
          java.naming:
            factory.initial: org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory
            provider.url: ${org.apache.activemq.url}
    incoming:
      from-indexingQueue:
        connector: helidon-jms
        destination: indexingQueue
        type: queue
      from-heatmapGeneration:
        connector: helidon-jms
        destination: heatmapGeneration
        type: queue
    outgoing:
      to-indexingQueue:
        connector: helidon-jms
        destination: indexingQueue
        type: queue
      to-heatmapGeneration:
        connector: helidon-jms
        destination: heatmapGeneration
        type: queue