version: '3.9'

services:
  react-ui:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - type: bind
        source: ../..
        target: /usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
