version: '3.9'

services:
  r2-ts-endpoint:
    build:
      context: ../../..
      dockerfile: install/docker/Dockerfile
    ports:
    - "8090:8090"
    env_file:
    - container.env
    volumes:
      - r2-ts-endpoint-log:/usr/share/r2ts/endpoint/log
    networks:
      - r2-ts
networks:
  r2-ts:
    external: true
volumes:
  r2-ts-endpoint-log:
    external: true