version: '3.9'

services:
  r2-ts-dataendpoint-base:
    build:
      context: ../../..
      dockerfile: install/docker/Dockerfile
    ports:
    - "8090:8090"
    env_file:
    - container.env
    networks:
      - r2-t2
networks:
  r2-t2:
    external: true